* Introduction

The irreversible illness-death model is a special multi-state model
which has many applications for example in medical research. The model
allows subjects to make transitions from an initial state (health) to
a terminal state (death) either directly or via an intermediate state
(disease), see Figure \ref{fig:1}.
#+source: idm1
#+BEGIN_SRC R :results graphics  :file "fig0.pdf" :exports none :cache yes 
library(prodlim)
plotIllnessDeathModel(stateLabels=c("0: Healthy","1: Diseased","2: Dead"),arrowLabelSymbol="alpha")
#+END_SRC
#+RESULTS[<2013-05-05 09:27:05> 38856dc9b3933d54da83656ebe4eb2f231a20b87]:
[[file:fig0.pdf]]

#+ATTR_LaTeX: :width 0.4\textwidth
#+LABEL: fig:1
#+CAPTION: The irreversible illness-death model
#+results: idm1
[[file:fig0.pdf]]
If the exact transition times are observed, standard procedures can be
used to estimate regression models for the three transitions
\citep{deWreede_Fiocco_Putter_2010}. In particular, the regression
coefficients can be estimated using Cox partial likelihood without the
need to specify the baseline intensities. However, this possibility is
lost when the transition times from the initial state to the transient
state are interval censored. For example, it may not be possible to
determine the exact onset time of dementia for a patient diagnosed at
time $R$. Instead it is only known that the patient was last seen
dementia-free at time $L$. Thus, the onset time is interval censored
between $L$ and $R$. The algorithms of the \pkg{SmoothHazard} package
implement methods for estimating regression models under this type of
censoring if the transition times into the absorbing state (e.g. death
of the patient) are either known exactly or right censored 
\citep{Joly_Commenges_Helmer_Letenneur_2002}. 

Implemented are a parametric and a semi-parametric estimation
approach. For the parametric approach, the Weibull distribution is
used for the baseline transition intensities and the parameters are estimated by maximising the likelihood. 
For the semi-parametric approach, M-splines are used to approximate the
baseline transition intensities and the parameters are estimated maximising a penalized
likelihood. The methods allow delayed entry of the subjects,
i.e. that the event times are left truncated.

Section 2 presents the model and the likelihood.
Section 3 presents the estimation methods.
Section 4 provides some examples illustrating \pkg{SmoothHazard} functions.

* Data, model and questions
In order to illustrate the functionality of the
package we provide a random subset containing data from 1000 subjects
that were enrolled in the Paquid study \citep{letenneur1999sex}, 
a large cohort study on mental and physical aging. 
#+BEGIN_SRC R :exports code :results silent :cache yes 
data(Paq1000)
#+END_SRC
The population consists of subjects aged 65 years and older living in
Southwestern France. 
The event of interest is dementia and death without
dementia is a competing risk. Furthermore, the time to dementia onset
is interval censored.

#+BEGIN_SRC R :exports none :results silent :cache yes 
n.demented <- sum(Paq1000$dementia)
n.died <- sum(Paq1000$death)
n.died.notdiagnosed <- sum(Paq1000$death & !Paq1000$dementia)
n.women <- sum(Paq1000$gender==0)
n.men <- sum(Paq1000$gender==1)
n.with <- sum(Paq1000$certif==0)
n.without <- sum(Paq1000$certif==1)
#+END_SRC

In this subset SRC_R{n.demented} subjects are diagnosed as demented
and SRC_R{n.died} died from whom SRC_R{n.died.notdiagnosed} without
being diagnosed as demented before. Because of interval censoring 
more than SRC_R{n.demented} should have been demented, more than (respectively more than 
SRC_R{n.died-n.died.notdiagnosed} should have been dead with dementia and
less than SRC_R{n.died.notdiagnosed} should have been dead with dementia
(see Figure \ref{fig:idm_nb_transitions}).
There are two covariates in this
subset: gender (SRC_R{n.women} women and SRC_R{n.men} men) and primary
school diploma (SRC_R{n.with} with diploma and SRC_R{n.without} without
diploma). Age is chosen as the basic time scale and subjects are non demented at entry into study. 
Consequently, we need to deal with left-truncated event times.

#+BEGIN_SRC R :exports both :results output :cache yes
head(Paq1000)
#+END_SRC

#+RESULTS[<2013-04-30 13:49:19> f6320ffa3c0dd5e062341b21b4486baef83212c3]:
:   dementia death   t0        l        r       t       certif gender
: 1        1     1 72.3333 82.34014 84.73303 87.93155      0      0
: 2        0     1 77.9167 78.93240 78.93240 79.60048      0      1
: 3        0     1 79.9167 79.91670 79.91670 80.92423      0      0
: 4        0     1 74.6667 78.64750 78.64750 82.93501      1      1
: 5        0     1 76.6667 76.66670 76.66670 79.16636      0      1
: 6        0     0 66.2500 71.38070 71.38070 84.16975      1      0

Each row in the data corresponds to one subject. 
The variables \code{dementia} and \code{death} are the status variables (1 for an event, 0 for right censoring) for events dementia and death, respectively.
The variable \code{t0} contains ages of subjects at entry. The variables \code{l} and \code{r} contain the left and right endpoints of the censoring intervals.
For demented subjects, \code{r} is the age at the diagnostic visit and \code{l} is the age at the previous one.
For non demented subjects, \code{l} and \code{r} are the age at the latest visit without dementia (\code{l}=\code{r}).
The variable \code{t} is the age at death or at latest news. \code{certif} and \code{gender} are binary covariates.

 # #+BEGIN_SRC R :results graphics  :file "~/Dropbox/JSS2013/manuscript_50/paq-idm.pdf" :exports both
 # library(prodlim)
 # plotIllnessDeathModel(stateLabels=c("Dementia free","Dementia","Death"),arrowLabelSymbol="alpha")
 # #+END_SRC

The function \code{idm} computes estimates for the
three transition intensities $\alpha_{01}$, $\alpha_{02}$, $\alpha_{12}$ which are
age-specific incidence of dementia, age-specific mortality rate of dementia-free subjects and age-specific mortality rate of demented sujects, respectively.
Proportional transition intensities regression models allow for covariates :
$$\alpha_{hl}(t|Z_{hli})=\alpha_{0hl}(t)\exp\{\beta_{hl}^T Z_{hli}\}; ~~~ hl \in \{01,02,12\}$$
where $\alpha_{0hl}$ are baseline transition intensities, $Z_{hli}$ are covariates vectors and 
$\beta_{hl}$ are vectors of associated regression parameters.

Covariates must be specified at the right side of the \code{formula01}, \code{formula02} and 
\code{formula12} arguments of the \code{idm} function (\code{~1} for no covariates).

Interval censoring and left truncation must be specified at the left side of the formula arguments using the \code{Hist} function.
For left-truncated data, the \code{entry} argument of \code{Hist} must contain the vector of delayed entry times.
For interval-censored data, the \code{time} argument of \code{Hist} must contain a list of the left and right endpoints of the intervals.

#+begin_latex
\begin{center}
\begin{figure}
\label{fig:idm_nb_transitions}
\centering
\begin{tikzpicture}[scale=1]
\node[draw] (nd) at (0,0) {dementia free};
\node[draw] (d) at (4,0) {dementia};
\node[draw] (dcd) at (2,-2) {death};
\draw[->,>=latex] (nd) -- (d)node[label=$\geq 186$,pos=0.5]{};
\draw[->,>=latex] (nd) -- (dcd) node[auto=right,pos=0.5]{$\leq 597$};
\draw[->,>=latex] (d) -- (dcd) node[auto=left,pos=0.5]{$\geq 127$};
\end{tikzpicture}
\caption{The exact number of transitions in the illness-death model with interval-censored time to disease is unknown.}
\end{figure}
\end{center}

#+end_latex

 # #+ATTR_LaTeX: :width 0.4\textwidth
 # #+LABEL: fig:2
 # #+CAPTION: The irreversible illness-death model has three transition intensities.
 # #+RESULTS[<2013-04-30 16:53:16> ba75f7433e9d7fc854a710dd837d90d7c76a26a1]: [[file:~/Dropbox/JSS2013/manuscript_50/paq-idm.pdf]]

A call of the \code{idm} function looks as follows:
#+BEGIN_SRC R :exports code :results silent :cache yes
fit <- idm(formula01=Hist(time=list(l,r),event=dementia,entry=t0)~certif,
           formula02=Hist(time=t,event=death,entry=t0)~certif+gender,
           formula12= ~ 1,
           data=Paq1000)
#+END_SRC
where the \code{data} argument contains the data frame in which to interpret the variables of \code{formula01}, \code{formula02} and \code{formula12}.

Note that the left side of \code{formula12} does not need to be filled because all the data 
informations are already contained in \code{formula01} and \code{formula02}.
In fact, the \code{formula12} argument is required only if we want the covariates impacting 
transition 12 different from those impacting transition 02.

Questions ?
TODO
   
* Fitting the illness-death model based on interval-censored data
The \code{idm} function computes estimates for the three transition intensities:
$$\alpha_{hl}(t|Z_{hli})=\alpha_{0hl}(t)\exp\{\beta_{hl}^T Z_{hli}\}; ~~~ hl \in \{01,02,12\}$$
In the situation where time to disease and time to death are not interval censored
the regression coefficients can be estimated by the partial likelihood
method \citep{coxpartial} without the need to specify or estimate the
baseline hazard functions $\alpha_{0hl}(t)$. For interval-censored
transition times to state 1 the situation is more complex. It turns
out that we have to estimate all parameters simultaneously
and that we need a model for the baseline transition intensity functions. This can
be seen by inspecting the likelihood function.

For subject $i$, let us denote the conditional event-free survival function by
$$S(t|Z_{01i},Z_{02i})=e^{- A_{01}(t|Z_{01i}) -A_{02}(t|Z_{02i})}$$
where ${A}_{hl}(.|Z_{hli})$ are the conditional cumulative intensity functions:
$${A}_{hl}(t|Z_{hli})=\int_0^t {\alpha}_{hl}(u|Z_{hli})du$$.

We set $\delta_{1i}=1$ ($\delta_{1i}=0$) if subject $i$ has (has not) been observed diseased,
and $\delta_{2i}=1$  ($\delta_{2i}=0$) if subject $i$ is (is not) dead.

If $\delta_{2i}=0$, $T_i$ is time to death; if $\delta_{2i}=0$, death event is right-censored at $T_i$.
We denote by $L_i$ and $R_i$ the interval censoring times.
If subject $i$ has been observed diseased at time $R_i$ and has last been seen non diseased at time $L_i$ ($L_i<R_i$),
time to disease is interval-censored between $L_i$ and $R_i$.
The likelihood contribution for subject $i$ is:

\begin{equation}
{\cal L}_i = \displaystyle
\dfrac{1}{S(T_{0i}|Z_{01i},Z_{02i})}
\int_{L_i}
^{R_i} S(u|Z_{01i},Z_{02i})
\alpha_{01}(u|Z_{01i}) \frac{
e^{-{A}_{12}(T_i|Z_{12i})}}{e^{-{A}_{12}(u|Z_{12i})}}\big(\alpha_{12}(T_i|Z_{12i})\big)^{\delta_{2i}}du
\end{equation}

If subject $i$ has never been seen diseased, time to disease is right-censored and the interval censoring times are set to the right censoring time ($L_i=R_i$).
The likelihood contribution for subject $i$ is:

\begin{multline}
\label{eq:likelihood2}
{\cal L}_i = \displaystyle
\dfrac{1}{S(T_{0i}|Z_{01i},Z_{02i})}
\Bigg( 
S(T_i|Z_{01i},Z_{02i})
\big(\alpha_{02}(T_i|Z_{02i})\big)^{\delta_{2i}} +\\
\int_{L_i}^{T_i} S(u|Z_{01i},Z_{02i})
\alpha_{01}(u|Z_{01i}) 
\frac{
e^{-{A}_{12}(T_i|Z_{12i})}}{e^{-{A}_{12}(u|Z_{12i})}}\big(\alpha_{12}(T_i|Z_{12i})\big)^{\delta_{2i}}du
\Bigg)
\end{multline}
If time to disease and time to death are both right-censored at the same time, we have $L_i=R_i=T_i$ and the integral value in (\ref{eq:likelihood2}) is zero.



** The Weibull parametrization

The default estimation method in function \code{idm} computes the maximum likelihood estimate for the three transition intensities 
using a Weibull parametrization for the baseline transition intensities: 
 $$ \alpha_{0hl}(t)= a_{hl} ~ b_{hl}^{a_{hl}} ~ t^{a_{hl}-1}; ~~~ hl \in \{01,02,12\}.$$
where $a_{hl}$ and $b_{hl}$ are shape and scale parameters.

#+BEGIN_SRC R :exports both :results output :cache yes 
fit.weib <- idm(formula02=Hist(time=t,event=death,entry=t0)~certif+gender,
                formula01=Hist(time=list(l,r),event=dementia,entry=t0)~certif+gender,
                data=Paq1000,intensities="Weib")
print(fit.weib)
#+END_SRC

#+RESULTS[<2013-04-30 13:49:56> c4a7cbcc4bb44796d4fcc1e6c405d63d54452162]:
#+begin_example
Call:
idm(formula01 = Hist(time = list(L, R), event = dementia) ~ certif + 
    gender, formula02 = Hist(time, event = death, entry = entry) ~ 
    certif + gender, data = Paq1000, maxiter = 200, eps = c(5, 
    5, 3), hazard = "Weib")

Illness-death Model using a parametric approach with a Weibull distribution for the intensity functions.

number of subjects:  1000 
number of events '0-->1':  186 
number of events '0-->2' or '0-->1-->2':  724 
number of covariates:  2 2 2 

             coef SE.coef     HR          CI       Wald  p.value
certif_01 -0.5194  0.2016 0.5949 [0.40;0.88]  6.6399364 0.009972
gender_01 -0.1221  0.1599 0.8851 [0.65;1.21]  0.5834324 0.444970
certif_02  0.1268  0.1264 1.1352 [0.89;1.45]  1.0066517 0.315706
gender_02  0.5363  0.1200 1.7096 [1.35;2.16] 19.9873828 < 0.0001
certif_12 -0.2079  0.2323 0.8123 [0.52;1.28]  0.8014211 0.370669
gender_12  0.5792  0.1865 1.7846 [1.24;2.57]  9.6469569 0.001897

               Without cov  With cov
Log likelihood   -3075.308 -3048.791

Parameters of the Weibull distribution: 'S(t) = exp(-(b*t)^a)'
      alpha01    alpha02    alpha12
a 11.18802187 8.62750163 7.50200265
b  0.01099806 0.01078284 0.01294115

----
Model converged.
number of iterations:  8 
convergence criteria: parameters= 0.00000012 
                    : likelihood= 0.0000007 
                    : second derivatives= 0.00000000047
#+end_example

\textit{Maximization algorithm}

The vectors of parameters for the baseline transition intensities
$a_{hl}$ and $b_{hl}$ and the vectors of
regression parameter $\hat \beta_{hl}$ are obtained simultaneously by maximizing the
log-likelihood using a combination of a Marquardt's algorithm \citep{Marquardt_1963} 
 which is a robust Newton-like algorithm and a steepest descent algorithm. 
Using the Marquardt's algorithm, few iterations are needed if the initial value 
is judiciously chosen.
The Marquardt's algorithm step involves a line
search with a step reduction if the new point is not better.
Using the steepest descent algorithm, the convergence is slower.
The steepest descent step involves a full line search and is attempted
only if the Marquardt's algorithm step has failed, due generally to a
difficulty to inverse the Hessian matrix of the log-likelihood.
We stop the iterations when the differences between two consecutive
parameters values, log-likelihood values, and gradient values is small enough.
The default convergence criteria are $10^{-5}$, $10^{-5}$ and $10^{-3}$ and 
can be changed by means of the \code{eps} argument. 
The variances of parameter estimates are estimated
using the inverse of the matrix of the second derivatives at
convergence.

** The penalized likelihood 

Another estimation method in \code{idm} permits to get smooth transition intensities 
without parametric specification.
Using the option \code{intensities="Splines"}, a maximum penalized likelihood estimate is computed
using a spline approximation for the three transition intensities $\alpha_{01}$, $\alpha_{02}$, $\alpha_{12}$.

To force smoothness of intensity functions, we penalize the likelihood by a
term relating to the curvature of the intensity functions that is the quare of the 
second derivates.

The penalized log-likelihood $(pl)$ is defined as:

\begin{equation}
\label{eq:77}
pl = l - \kappa_{01} \int {\alpha_{01} ^{''} }^2 (u) du - \kappa_{12}
\int {\alpha_{12} ^{''} }^2 (u) du - \kappa_{02} \int {\alpha_{02}
^{''} }^2 (u) du \ \ \ \
\end{equation}

where $l$ is the log-likelihood and
$\kappa_{01}$, $\kappa_{02}$ and $\kappa_{12}$ are three positive
smoothing parameters which control the trade-off between the data fit
and the smoothness of the functions.

Maximization of (\ref{eq:77}) defines the maximum penalized likelihood
estimators (MPLE) ${\hat \alpha_{01}}$, ${\hat \alpha_{02}}$ and
${\hat \alpha_{12}}$.\\

\bigskip

\textit{Approximation via splines}

A spline of order $k$ is a piecewise polynomial functions of degree $k-1$. 
The places where the polynomial pieces connect are the knots.
Associated with a knot sequence $t$, basis splines can be combined linearly to yield 
any other spline associated with $t$.
${\hat \alpha_{01}}$, ${\hat \alpha_{02}}$ and ${\hat \alpha_{12}}$ 
are approximated using linear combination of $M$-splines \citep{Ramsay_1988}. 
For $hl \in \{01,02,12\}$:
$$ \tilde \alpha_{hl}(x)=\sum_{i=1}^n a_i M_i(x)  $$ 
where $n$ is the number of free parameters.\\
The non-negativity of $\tilde \alpha_{hl}$ is assured by constraining 
the coefficients $a_i$ to be positive.
In practice, we estimate parameters $\theta_i$ such that $a_i=\theta_i^2$
which maximize the penalized likelihood.


A $M$-spline of order $k$ is computed using the following recursion:

For $k=1$,
\begin{eqnarray*}
M _{j} (x |1,t)& = &\left\{
  \begin{array}{ll}
  \frac {1}{(t_{j+1}-t_{j})} \ \ \ \ \mbox{if} \ \ t_j \leq x < t_{j+1}\\
  0 \ \ \ \ \ \ \ \ \ \ \ \ \ \mbox{elsewhere} \\
  \end{array}
\right.\\
\end{eqnarray*}

For $k>1$,
\begin{eqnarray*}
M _{j} (x |k,t)& = & \left\{
  \begin{array}{ll}
  \frac { k \left[ (x-t _{j})M_{j} (x |k-1,t)+ (t_{j+k}-x)M_{j+1} (x |k-1,t)
  \right]}{(k-1)(t_{j+k}-t_{j})} \ \ \ \mbox{if} \ \ t_j \leq x < t _{j+k}\\
  0 \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \
\ \ \ \ \ \ \ \ \ \ \ \  \ \ \ \mbox{elsewhere} \\
\end{array}
\right.
\end{eqnarray*}

where $t={t_1,...,t_{n+k}}$ is a knot sequence.

The $M$-spline family is particularly appealing to statisticians because each $M_i$
has the properties of a probability density function over the interval $[t_i,t_{i+k}]$.
Among them, we have $\int M_i(x) dx = 1$

One can associate to each $M$-spline, the integrated splines or $I$-splines 
$I_i$, $i=1,\ldots,n$ such that $I_i(x|k,t)=\int_{t_k}^x M_i(u|k,t) du$.
Given the coefficients $a_i$, we can approximate estimators of the 
cumulative transition intensities $\hat A_{hl}$ using a linear combination of $I$-splines:
$$ \tilde A_{hl}(x)=\sum_{i=1}^n a_i I_i(x) $$
Because $M$-splines are non-negative, the positivity constraint on $a_i$ ensures that 
the $\tilde A_{hl}$ are monotically increasing.
Each $M_j$ is piecewise polynomial of degree $k-1$ and each associated
$I_j$ is piecewise polynomial of degree $k$. 
In the package we use cubic $M$-splines \textit{i.e.} $k=4$.

\bigskip

\textit{Choice of the knots}

The knots sequence has some properties to ensure continuity conditions. Among them, we have:
$t_1=\ldots=t_k$ and $t_{n+1}=\ldots=t_{n+k}$.
The number of free parameters $n$ corresponds to $k+$ the number of knots 
interior to $[t_k,t_{n+1}]$

In \pkg{SmoothHazard}, the knots are put equidistantly between them 
by default. The \code{knots} argument can be fulfilled to choose their location freely
but in general the shape of a spline function is not very sensitive to knot placement.
However, there must be several data points between each pair of different knots and 
there must be a knot before or at the first data point and after or at the last data point.
Increasing the number of data points between a pair of knots leads to a better defined curve.

The number of knots can be specified in the \code{n.knots} argument. It must be
understood as the number of different knots \textit{i.e.} 
the number of knots from $t_k$ to $t_{n+1}$. 
The default is 7 on the three transitions which leads to 
a number of free parameters one one transition $n=3+5=9$.
Increasing the number of knots in a region leads to 
a greater flexibility of the function in that region.
The number of knots and their location can be chosen differently for each transition.

\bigskip

\textit{Smoothing parameters}

The default values for the smoothing parameters are suitable for the avalaible 
\code{Paq1000} data set. However, these values can be expected to be very different 
depending on time scale and number of subjects. 
They can be changed into the \code{kappa} argument.
An approximate cross-validation technique to determine the smoothing parameters 
is also available with the option \code{CV=TRUE}.
In this case, the \code{kappa} argument contains the initial values for the smoothing parameters.
We use an approximate leave-one-out score proposed by \citet{O'Sullivan_1988} for survival models 
and extended for multi-state models \citep{Commenges_Joly_Gegout-Petit_Liquet_2007} for which only one estimation of the model is required 
by tested values of the smoothing parameters.

\bigskip

\textit{Maximization algorithm}

The vectors of spline coefficients for fixed $\kappa_{01}$, $\kappa_{12}$ and $\kappa_{02}$
and the vectors of regression parameters $\hat \beta_{01}$, $\hat \beta_{02}$,  $\hat \beta_{12}$
are obtained simultaneously by maximizing the penalized log-likelihood using the same 
maximization algorithm as with the Weibull parametrization (see Section \ref{sec-3-1}).

\bigskip

\textit{Practical advices}

Increasing the number of knots does not deteriorate the MPLE: this is
because the degree of smoothing in the penalized likelihood method is
tuned by the smoothing parameters $\kappa_{01}$, $\kappa_{12}$ and
$\kappa_{02}$.
On the other hand, once a sufficient number of knots is established,
there is no advantage in adding more.
Moreover, the more knots, the longer the running time.
Some numerical problem
can arise, particularly for a large number of knots. That is why the
maximum number of knots is limited to 25. So it is recommended to
start with a small number of knots (e.g. 5 or 7) and increase the number of
knots until the graph of the transition intensities function remains unchanged (rarely
more than 12 knots). 

The choice of the smothing parameters can be fastidious. 
The \code{idm} function can be run with the approximate cross-validation option.
However, the running time is very long and an empirical technique can be preferred.
It consists in repeting the idm running trying different smoothing parameters.
After each estimation, the transition intensities must be plotted, for example 
with the \code{plot} function. 
For the curves that seem over-smooth, the associated smoothing parameter must be reduced.
For the curves that seem under-smooth, the associated smoothing parameter must be increased.


#+BEGIN_SRC R :results graphics :file "~/Dropbox/JSS2013/manuscript_50/transition-intensities-paq-weib.pdf" :exports results
plot(fit.weib,conf.int=TRUE)
#+END_SRC

 # #+RESULTS[<2013-04-30 16:27:45> a85422472c3b7b3bb92da9751c2b751b59bb30fc]:[[file:~/Dropbox/JSS2013/manuscript_50/transition-intensities-paq-weib.pdf]]

* Predicting parameters of life

Most often in illness-death models, the functions of interest are the transition intensities. 
In our application, $\alpha_{01}(.)$, $\alpha_{02}(.)$ and $\alpha_{12}(.)$ corresponds to
age-specific incidence of dementia, age-specific mortality rate of non demented subjects 
and age-specific mortality rate of demented subjects.
However, other functions/quantities which can be expressed in terms of the 
transition intensities \citep{Touraine_2013} and
may provide additional information and have a more natural interpretation.

The fonction \code{idm} returns an ``idmWeib'' or ``idmSplines'' class object
depending on the parametrization of the transition intensities (Weibull or splines).
These objects can be used in argument of the \code{predict.idmWeib} and \code{predict.idmSplines} 
functions in order to obtain transition probabilities between ages 70 and 80 (and cumulative probabilities).
For example, for a female subject who is healthy at age 70 and has primary school certificate: 
#+BEGIN_SRC R :exports both :results output :cache yes 
TP <- predict(fit.weib,s=70,t=80,Z01=c(1,0),Z02=c(1,0),Z12=c(1,0))
TP
#+END_SRC

where \code{TP$p00}, \code{TP$p01}, \code{TP$p11}, \code{TP$p02} are the transition probabilities; 
\code{TP$p02_1} and \code{TP$p02_0} are the probabilities of transition from state 0 to state 2 coming through state 1 or not;
\code{F01} is the probability for of becoming diseased between ages 70 and 80;
\code{F0.} is the probability of exit from state 0 between ages 70 and 80.

If the \code{predict} function is used with an \code{idmSplines} object, the \code{s} input must be greater than the first knot and the \code{t} input must be lower than the last knot.

The ``idmWeib'' or ``idmSplines'' objects can also be used in argument of the \code{lifexpect}
function to obtain life expectancies. For example, for a female subjects who has primary school certificate, the following code:
#+BEGIN_SRC R :exports both :results output :cache yes
LE_fit.weib <- lifexpect(fit.weib,s=90,Z01=c(1,0),Z02=c(1,0),Z12=c(1,0),CI=FALSE)
LE_fit.weib
#+END_SRC
produces healthy life expectancy, life expectancy for a non diseased subject and life expectancy for a diseased subject.
Again, if this function is used with an \code{idmSplines} object, the \code{s} input must be greater than the first knot. 
Moreover, life expectancies are calculated integrating up to infinity using an ``idmWeib'' object but up to the last knot using an ``idmSplines'' object.
Consequently using an ``idmSplines'' object, it must be acceptable to assume that any subject should be in state 2 (dead) at the age corresponding to the last knot. 
Otherwise, the life expectancies would be underestimated.

  # \bibliographystyle{apalike}
\bibliography{smoothhazard}

* COMMENT Latex header
#+TITLE: Fitting regression models to interval-censored observations of illness-death models
#+LANGUAGE:  en
#+OPTIONS:   H:3 num:t toc:nil \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil tags:not-in-toc author:nil creator:nil
#+LaTeX_CLASS: jss
#+LATEX_HEADER: \usepackage{tikz}
#+LATEX_HEADER: \usepackage{hyperref}
#+LATEX_HEADER: \usepackage{amsmath}
#+LATEX_HEADER: \usepackage{attrib}
#+LATEX_HEADER: \Plainauthor{C\'elia Touraine, Thomas A. Gerds, Pierre Joly}
#+LATEX_HEADER: \author{C\'elia Touraine\\University of Bordeaux \And Thomas A. Gerds\\University of Copenhagen \And Pierre Joly\\University of Bordeaux}
#+LATEX_HEADER: \title{Illness-Death Model for Interval-Censored Data: The \pkg{SmoothHazard} Package for \proglang{R}}
#+LATEX_HEADER: \Shorttitle{Illness-Death Model for Interval-Censored Data: The  \pkg{SmoothHazard} Package for \proglang{R}}
#+LATEX_HEADER: \Keywords{illness-death model, interval-censored data, left-truncated data, survival model, proportional regression models, Smooth Transition intensities, Weibull}
#+LATEX_HEADER: \Address{C\'elia Touraine\\Univ. Bordeaux\\ISPED\\Centre INSERM U-897-Epidemiologie-Biostatistique\\Bordeaux F-33000\\France\\E-mail: celia.touraine@isped.u-bordeaux2.fr\\URL: http://www.isped.u-bordeaux2.fr/}
#+LATEX_HEADER: \Abstract{\input{jss-abstract.tex}}
#+LATEX_HEADER: \lstset{
#+LATEX_HEADER: keywordstyle=\color{blue},
#+LATEX_HEADER: commentstyle=\color{red},
#+LATEX_HEADER: stringstyle=\color[rgb]{0,.5,0},
#+LATEX_HEADER: basicstyle=\ttfamily\small,
#+LATEX_HEADER: columns=fullflexible,
#+LATEX_HEADER: breaklines=true,        % sets automatic line breaking
#+LATEX_HEADER: breakatwhitespace=false,    % sets if automatic breaks should only happen at whitespace
#+LATEX_HEADER: numbers=left,
#+LATEX_HEADER: numberstyle=\ttfamily\tiny\color{gray},
#+LATEX_HEADER: stepnumber=1,
#+LATEX_HEADER: numbersep=10pt,
#+LATEX_HEADER: backgroundcolor=\color{white},
#+LATEX_HEADER: tabsize=4,
#+LATEX_HEADER: showspaces=false,
#+LATEX_HEADER: showstringspaces=false,
#+LATEX_HEADER: xleftmargin=.23in,
#+LATEX_HEADER: frame=single,
#+LATEX_HEADER: basewidth={0.5em,0.4em}
#+LATEX_HEADER: }
#+LaTeX_HEADER:\usepackage{graphicx}
#+LaTeX_HEADER:\usepackage{array}
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+STARTUP: oddeven
#+PROPERTY: session *R* 
#+PROPERTY: cache yes
